name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the Docker image
        run: docker build -t my-mlops-project .
      - name: Run tests
        run: pytest
      - name: Push Docker image
        run: docker push my-mlops-project
